name: Docker Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER-UNAME }}
        password: ${{ secrets.DOCKERHUBPASSWORD }}

    - name: Build Docker Image
      run: docker build -t varshathorat/guestbook-go:latest .

    - name: Push Docker Image
      run: docker push varshathorat/guestbook.go:latest
