name: Docker Build and Publish

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
  name: push docker image to Docker Hub
  runs-on: ubuntu-latest
 steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERHUBPASSWORD }}

    - name: Build Docker Image
      run: docker build -t varshathorat/guestbook_go:latest .

    - name: Push Docker Image
      run: docker push varshathorat/guestbook_go:latest
